title: Kalco Documentation
description: Kubernetes Analysis & Lifecycle Control - Comprehensive cluster management tool
url: https://graz-dev.github.io
# baseurl: /kalco  # Uncomment for GitHub Pages deployment, comment for local development

# Theme
remote_theme: just-the-docs/just-the-docs

# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Plugins
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

# Defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
      author: "Graz Dev"

# Just the Docs configuration
just_the_docs:
  # Color scheme supports "light" (default) and "dark"
  color_scheme: light
  
  # Enable search
  search: true
  
  # Enable search header button
  search_full_words: false
  
  # Heading anchor links appear on hover over h1-h6 tags
  heading_anchors: true
  
  # Enable smooth scrolling
  scroll_to_top: true
  
  # Enable back to top button
  back_to_top: true
  
  # Enable back to top button
  back_to_top_text: "Back to top"
  
  # Enable footer content
  footer_content: "Copyright &copy; 2025 Graz Dev. Made with ❤️ for the Kubernetes community."
  
  # Enable last modified date
  last_edit_timestamp: true
  
  # Enable git info
  git_info: true

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git
  - README.md
