# GitHub Pages Configuration for Kalco Documentation
title: Kalco Documentation
description: Kubernetes Analysis & Lifecycle Control
baseurl: "/kalco"
url: "https://graz-dev.github.io"

# Build settings
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-seo-tag

# Collections
collections:
  docs:
    output: true
    permalink: /:collection/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "docs"
    values:
      layout: "default"
      author: "Graz Dev"

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git