title: Kalco Documentation
description: Kubernetes Analysis & Lifecycle Control - Comprehensive cluster management tool
url: https://graz-dev.github.io/kalco
baseurl: ""

# Theme
remote_theme: jekyll/minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-remote-theme

# Navigation
header_pages:
  - getting-started.md
  - commands/index.md
  - configuration.md
  - use-cases.md
  - contributing.md
  - faq.md

# SEO
author: Graz Dev
twitter:
  username: grazdev
  card: summary_large_image

# Social links
github_username: graz-dev

# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Permalink structure
permalink: pretty

# Default layouts
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/