name: Dependencies

on:
  schedule:
    # Run every Monday at 9 AM UTC
    - cron: '0 9 * * 1'
  workflow_dispatch: # Allow manual trigger

jobs:
  update-deps:
    name: Update Dependencies
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Check for updates
        id: nancy
        run: |
          # Install nancy for vulnerability scanning
          go install github.com/sonatype-nexus-community/nancy@latest
          
          # Check for vulnerabilities
          go list -json -deps | nancy sleuth
          
          # Check for updates
          go list -u -m all

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'chore(deps): update dependencies'
          title: 'chore(deps): update dependencies'
          body: |
            ## 🔄 Dependency Updates
            
            This PR updates dependencies to their latest versions.
            
            ### Changes
            - Updated Go dependencies
            - Security vulnerability fixes
            - Performance improvements
            
            ### Checklist
            - [ ] Tests pass
            - [ ] No breaking changes
            - [ ] Security scan clean
            
            ### Security
            - [ ] Dependencies scanned for vulnerabilities
            - [ ] All known CVEs addressed
            
            ---
            
            *Auto-generated by GitHub Actions*
          branch: update-dependencies
          delete-branch: true
          labels: |
            dependencies
            automated
            security
