name: Release Drafter

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types: [ opened, reopened, synchronize ]

jobs:
  update_release_draft:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5
        id: release_drafter
        with:
          name: Release ${{ steps.release_drafter.outputs.tag_name }}
          tag_name: ${{ steps.release_drafter.outputs.tag_name }}
          body: ${{ steps.release_drafter.outputs.body }}
          draft: true
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
